version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    #environment:
    #  - BACKEND_URL=http:127.0.0.1:8000 # Backend URL without trailing slash
    stdin_open: true
    tty: true
